[Main]
#########################################################################
# RosssTalk/Byte Encoded String Listen Port
# Will Mount listeners on this port for all Network Interfaces
#########################################################################
# Supports multiple ports allowing multiple devices to connect
# For multiple ports, separate the values with a comma
# Example: 7788,7789,7790
#########################################################################
listen_port = 7788

#########################################################################
# IP address of Prompter system to connect to. 
# Most common use case is to run the application on the Prompter system 
# directly. In the case use: 127.0.0.1
#########################################################################

prompt_ip = 127.0.0.1

#########################################################################
# Prompter API listen port. Default: 443
#########################################################################

prompt_port = 443

###################################################################################################
# Prompter automation (API) username and password.
# The Default values are:
#	username: default
#	password: winplus
# Password can be changed in Winplus. Settings --> Automation Interface --> Change Password
###################################################################################################
username = default
password = winplus

###################################################################################################
#The KEY value is used in the RossTalk Command to reference Overdrive at a particular IP address
# EXAMPLE Rosstalk: 
#	LOAD_PCR_RUNDOWN PCR2
#
#       Would Query the Overdrive at 10.218.116.11, and load the rundown based on the rundown that is being 
#       played out. If Overdrive was playing the 5PM Newscast, this commmand would load the 5pm Newscast into the 
#       prompter.
#
# Place any value for PCR. The default is PCR1 & PCR2. Delete PCR2 if only one control room is used
# Use the IP address on the Overdrive Primary Server for that control room
###################################################################################################

[Control Room]
PCR1 = PCR1_Overdrive_Primary_ip
PCR3 = 10.218.116.111

# ######################################################################################################
# KEY = Client PC Name
# VALUE = Client PC IP address
# These values are used to track whether the Primary or Backup Server is Active
# 
# Associates the Name of the Client PC with that's active as reported by floor director with it's IP address
# KGO Example:
#	OW-CASF-2ODCLIA = 10.218.116.11
#	OW-CASF-2ODCLIB = 10.218.116.12
#	OW-CASF-3ODCLIA = 10.218.116.111
#	OW-CASF-3ODCLIB = 10.218.116.112
# ######################################################################################################

[Clients]
OW-CASF-XXXX = PCR1_Overdrive_Primary_IP
OW-CASF-XXXX = PCR1_Overdrive_Redundant_IP
OW-CASF-XXXX = PCR2_Overdrive_Primary_IP
OW-CASF-XXXX = PCR2_Overdrive_Redundant_IP

# ######################################################################################################
# These are the default floordirector endpoints
# ######################################################################################################

[Floor Director]
info_endpoint = /server/floordirector/api/v1/info?
shots_endpoint = /server/floordirector/api/v1/shots?

# ######################################################################################################
# server: This is the name of the Dalet SQL Database
# database: DaletDB is the default Value
# username: Leave this as-is
# password: leave this as-is
# ######################################################################################################
# The Username and Password are not explicitly needed. Current versions of MSSQL require the current user
# account to have administrator level permissions
# ######################################################################################################

[Dalet]
server = OM-CASF-DLSQL
database = DaletDB
username = $kgotvscripts
password = ABC7news